---
queue_rules:
  - name: default
    conditions:
      - "status-success=Travis CI - Pull Request"
      - status-success=WIP

pull_request_rules:
  - name: automatic merge and new release from cloudalchemybot
    conditions:
      - "status-success=Travis CI - Pull Request"
      - status-success=WIP
      - head~=autoupdate|skeleton
      - author=cloudalchemybot
    actions:
      queue:
        method: merge
        name: default
