---
- name: restart prometheus
  become: true
  systemd:
    daemon_reload: true
    name: {{ prometheus_systemd_service_name }}
    state: restarted

- name: reload prometheus
  become: true
  systemd:
    name: {{ prometheus_systemd_service_name }}
    state: reloaded
