---
- name: Prepare
  hosts: localhost
  gather_facts: false
  vars:
    # This is meant to test a local prepared binary. It needs to be updated to support the minium
    # flag features in the systemd service file.
    version: 2.25.2
  tasks:
    - name: download prometheus binary to local folder
      become: false
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ version }}.linux-amd64.tar.gz"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      run_once: true
      check_mode: false

    - name: unpack prometheus binaries
      become: false
      unarchive:
        src: "/tmp/prometheus-{{ version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        creates: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
      run_once: true
      check_mode: false

    - name: link to prometheus binaries directory
      become: false
      file:
        src: "/tmp/prometheus-{{ version }}.linux-amd64"
        dest: "/tmp/prometheus-linux-amd64"
        state: link
      run_once: true
      check_mode: false
